spring:
  application:
    name: jobs
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  sql:
    init:
      mode: always
      continue-on-error: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_REALM_URL}
#          jwk-set-uri: ${OAUTH2_REALM_URL}/protocol/openid-connect/certs

springdoc:
  swagger-ui:
    enabled: true
  oauth2:
    authUrl: ${OAUTH2_REALM_URL}/protocol/openid-connect/auth
    tokenUrl: ${OAUTH2_REALM_URL}/protocol/openid-connect/token

server:
  port: ${PORT:8080}
  error:
    include-stacktrace: always
    whitelabel:
      enabled: false