spring:
  application:
    name: jobs
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  sql:
    init:
      mode: always
      continue-on-error: true

server:
  port: 8080
  error:
    include-stacktrace: always
    whitelabel:
      enabled: false
