CREATE TABLE IF NOT EXISTS company (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  city VARCHAR(128),
  street VARCHAR(128),
  zip VARCHAR(8),
  contact TEXT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS job (
  id SERIAL PRIMARY KEY,
  company_id INTEGER NOT NULL,
  title VARCHAR(255) NOT NULL,
  remarks TEXT,
  closed BOOL DEFAULT FALSE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT job_company_id_fkey FOREIGN KEY (company_id)
    REFERENCES company (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS interview (
  id SERIAL PRIMARY KEY,
  job_id INTEGER NOT NULL,
  url TEXT,
  remarks TEXT,
  date TIMESTAMP,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT interview_job_id_fkey FOREIGN KEY (job_id)
    REFERENCES job (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);
